### ISSUE TITLE
INFLUXDB_HTTP_AUTH_ENABLED variable

### ISSUE THREAD

**Issue by dontsovcmc** [ratibor78/influxdb-grafana-docker#1]
https://github.com/influxdata/influxdata-docker/issues/281#issuecomment-465417635

init-influxdb.sh won't do anything if the environment variable for HTTP auth isn't set. 
 -e INFLUXDB_HTTP_AUTH_ENABLED=true

**Comment by ratibor78** [comment]
Thanks, will fix this option.

**Comment by ratibor78** [comment]
Fixed
